{% set name = "stripy" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stripy-{{ version }}.tar.gz
  sha256: afc10284f77f901b00fbee4538e1c6541ae4be1db690e474a7bf9249aecc76b2

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python
    - {{ compiler('fortran') }}

  host:
    - python
    - pip
    - numpy

  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
    - setuptools # for pkg_resources

  source_files:
    - stripy/tests

  commands:
    - pytest

about:
  home: https://github.com/underworldcode/stripy
  license: LGPL-2.0-or-later
  license_family: GPL
  license_file: COPYING.LESSER
  summary: Python interface to TRIPACK and STRIPACK fortran code for triangulation/interpolation in Cartesian coordinates and on a sphere
  doc_url: https://underworldcode.github.io/stripy/2.1.1
  dev_url: https://github.com/underworldcode/stripy

extra:
  recipe-maintainers:
    - lmoresi
    - brmather
    - rbeucher
